import {
  Monitor,
  Smartphone,
  Laptop,
  Users,
  Server,
  Database,
  Globe,
  Zap,
  GitBranch,
  Scale,
  MessageSquare,
  Shield,
  HardDrive,
  Cloud,
  Cpu,
  Shuffle,
  ShieldAlert,
  Cog,
  Boxes,
  TableProperties,
  Search,
  BarChart,
  Radio,
  Bell,
  Video,
  Play,
  Brain,
  Key,
  Hourglass,
  Network,
  Activity,
  Flame
} from 'lucide-react';

export const COMPONENT_TYPES = [
  // --- CLIENTS ---
  {
    type: 'frontend',
    label: 'Web Client',
    icon: Monitor,
    color: '#3b82f6',
    bg: 'rgba(59,130,246,0.12)',
    border: 'rgba(59,130,246,0.4)',
    description: 'Web Application UI',
    category: 'Client',
  },
  {
    type: 'mobile',
    label: 'Mobile Client',
    icon: Smartphone,
    color: '#3b82f6',
    bg: 'rgba(59,130,246,0.12)',
    border: 'rgba(59,130,246,0.4)',
    description: 'iOS / Android App',
    category: 'Client',
  },
  {
    type: 'desktop',
    label: 'Desktop Client',
    icon: Laptop,
    color: '#60a5fa',
    bg: 'rgba(96,165,250,0.12)',
    border: 'rgba(96,165,250,0.4)',
    description: 'macOS / Windows App',
    category: 'Client',
  },
  {
    type: 'user',
    label: 'User / Actor',
    icon: Users,
    color: '#93c5fd',
    bg: 'rgba(147,197,253,0.12)',
    border: 'rgba(147,197,253,0.4)',
    description: 'End User / Client Request',
    category: 'Client',
  },

  // --- ROUTING & NETWORK ---
  {
    type: 'dns',
    label: 'DNS Server',
    icon: Network,
    color: '#06b6d4',
    bg: 'rgba(6,182,212,0.12)',
    border: 'rgba(6,182,212,0.4)',
    description: 'Domain Resolution',
    category: 'Network',
  },
  {
    type: 'cdn',
    label: 'CDN (Edge)',
    icon: Globe,
    color: '#06b6d4',
    bg: 'rgba(6,182,212,0.12)',
    border: 'rgba(6,182,212,0.4)',
    description: 'Content Delivery Network',
    category: 'Network',
  },
  {
    type: 'api_gateway',
    label: 'API Gateway',
    icon: GitBranch,
    color: '#eab308',
    bg: 'rgba(234,179,8,0.12)',
    border: 'rgba(234,179,8,0.4)',
    description: 'API Routing & Throttling',
    category: 'Network',
  },
  {
    type: 'load_balancer',
    label: 'Load Balancer',
    icon: Scale,
    color: '#ec4899',
    bg: 'rgba(236,72,153,0.12)',
    border: 'rgba(236,72,153,0.4)',
    description: 'Traffic Distribution',
    category: 'Network',
  },
  {
    type: 'reverse_proxy',
    label: 'Reverse Proxy',
    icon: Shuffle,
    color: '#14b8a6',
    bg: 'rgba(20,184,166,0.12)',
    border: 'rgba(20,184,166,0.4)',
    description: 'Nginx / HAProxy',
    category: 'Network',
  },
  {
    type: 'firewall',
    label: 'Firewall',
    icon: ShieldAlert,
    color: '#ef4444',
    bg: 'rgba(239,68,68,0.12)',
    border: 'rgba(239,68,68,0.4)',
    description: 'Network Shield / WAF',
    category: 'Network',
  },

  // --- SERVERS & COMPUTE ---
  {
    type: 'backend',
    label: 'Backend Server',
    icon: Server,
    color: '#22c55e',
    bg: 'rgba(34,197,94,0.12)',
    border: 'rgba(34,197,94,0.4)',
    description: 'App Server (Rails/Node/Go)',
    category: 'Compute',
  },
  {
    type: 'microservice',
    label: 'Microservice',
    icon: Cpu,
    color: '#84cc16',
    bg: 'rgba(132,204,22,0.12)',
    border: 'rgba(132,204,22,0.4)',
    description: 'Independent Domain Service',
    category: 'Compute',
  },
  {
    type: 'lambda',
    label: 'Serverless Func',
    icon: Zap,
    color: '#f59e0b',
    bg: 'rgba(245,158,11,0.12)',
    border: 'rgba(245,158,11,0.4)',
    description: 'FaaS (Lambda/Cloud Function)',
    category: 'Compute',
  },
  {
    type: 'worker',
    label: 'Bg Worker',
    icon: Cog,
    color: '#10b981',
    bg: 'rgba(16,185,129,0.12)',
    border: 'rgba(16,185,129,0.4)',
    description: 'Background Job Processor',
    category: 'Compute',
  },
  {
    type: 'k8s',
    label: 'Kubernetes Pod',
    icon: Boxes,
    color: '#326ce5',
    bg: 'rgba(50,108,229,0.12)',
    border: 'rgba(50,108,229,0.4)',
    description: 'Containerized Deployment',
    category: 'Compute',
  },

  // --- CACHE ---
  {
    type: 'cache',
    label: 'Redis Cache',
    icon: Zap,
    color: '#f97316',
    bg: 'rgba(249,115,22,0.12)',
    border: 'rgba(249,115,22,0.4)',
    description: 'In-Memory Cache (Redis)',
    category: 'Caching',
  },
  {
    type: 'memcached',
    label: 'Memcached',
    icon: Flame,
    color: '#fdba74',
    bg: 'rgba(253,186,116,0.12)',
    border: 'rgba(253,186,116,0.4)',
    description: 'Key-Value Memory Cache',
    category: 'Caching',
  },

  // --- STORAGE & DATABASES ---
  {
    type: 'database',
    label: 'SQL Database',
    icon: Database,
    color: '#a855f7',
    bg: 'rgba(168,85,247,0.12)',
    border: 'rgba(168,85,247,0.4)',
    description: 'Relational DB (Postgres/MySQL)',
    category: 'Storage',
  },
  {
    type: 'nosql',
    label: 'NoSQL DB',
    icon: TableProperties,
    color: '#c084fc',
    bg: 'rgba(192,132,252,0.12)',
    border: 'rgba(192,132,252,0.4)',
    description: 'Document/Wide-column Store',
    category: 'Storage',
  },
  {
    type: 'storage',
    label: 'Object Storage',
    icon: HardDrive,
    color: '#8b5cf6',
    bg: 'rgba(139,92,246,0.12)',
    border: 'rgba(139,92,246,0.4)',
    description: 'Files / Blobs (S3/Cloud Store)',
    category: 'Storage',
  },
  {
    type: 'search_engine',
    label: 'Search Engine',
    icon: Search,
    color: '#e879f9',
    bg: 'rgba(232,121,249,0.12)',
    border: 'rgba(232,121,249,0.4)',
    description: 'Elasticsearch / Vector DB',
    category: 'Storage',
  },
  {
    type: 'data_warehouse',
    label: 'Data Warehouse',
    icon: BarChart,
    color: '#a21caf',
    bg: 'rgba(162,28,175,0.12)',
    border: 'rgba(162,28,175,0.4)',
    description: 'Snowflake / BigQuery',
    category: 'Storage',
  },

  // --- MESSAGING & STREAMING ---
  {
    type: 'queue',
    label: 'Message Queue',
    icon: MessageSquare,
    color: '#14b8a6',
    bg: 'rgba(20,184,166,0.12)',
    border: 'rgba(20,184,166,0.4)',
    description: 'Async Tasks (RabbitMQ/SQS)',
    category: 'Messaging',
  },
  {
    type: 'kafka',
    label: 'Event Stream',
    icon: Radio,
    color: '#f97316',
    bg: 'rgba(249,115,22,0.12)',
    border: 'rgba(249,115,22,0.4)',
    description: 'Event Hub (Kafka/Kinesis)',
    category: 'Messaging',
  },
  {
    type: 'notification',
    label: 'Notification',
    icon: Bell,
    color: '#fbbf24',
    bg: 'rgba(251,191,36,0.12)',
    border: 'rgba(251,191,36,0.4)',
    description: 'Push / SMS / Email Dispatcher',
    category: 'Messaging',
  },

  // --- STREAMING & DATA PIPELINES (Netflix/YouTube) ---
  {
    type: 'transcoder',
    label: 'Video Transcoder',
    icon: Video,
    color: '#f43f5e',
    bg: 'rgba(244,63,94,0.12)',
    border: 'rgba(244,63,94,0.4)',
    description: 'HLS/DASH Chunks Encoder',
    category: 'Media',
  },
  {
    type: 'media_server',
    label: 'Media Server',
    icon: Play,
    color: '#ec4899',
    bg: 'rgba(236,72,153,0.12)',
    border: 'rgba(236,72,153,0.4)',
    description: 'Video Origin Streaming Server',
    category: 'Media',
  },

  // --- SECURITY, DEVOPS & ANALYTICS ---
  {
    type: 'auth',
    label: 'Auth Service',
    icon: Shield,
    color: '#f43f5e',
    bg: 'rgba(244,63,94,0.12)',
    border: 'rgba(244,63,94,0.4)',
    description: 'OAuth / JWT Provider',
    category: 'Security & Ops',
  },
  {
    type: 'iam',
    label: 'IAM / Keycloak',
    icon: Key,
    color: '#fda4af',
    bg: 'rgba(253,164,175,0.12)',
    border: 'rgba(253,164,175,0.4)',
    description: 'Identity Access Management',
    category: 'Security & Ops',
  },
  {
    type: 'rate_limiter',
    label: 'Rate Limiter',
    icon: Hourglass,
    color: '#fda4af',
    bg: 'rgba(253,164,175,0.12)',
    border: 'rgba(253,164,175,0.4)',
    description: 'Token Bucket Rate Limiter',
    category: 'Security & Ops',
  },
  {
    type: 'monitoring',
    label: 'Monitoring',
    icon: Activity,
    color: '#10b981',
    bg: 'rgba(16,185,129,0.12)',
    border: 'rgba(16,185,129,0.4)',
    description: 'Prometheus / Grafana Analytics',
    category: 'Security & Ops',
  },
  {
    type: 'ml_service',
    label: 'ML Rec Engine',
    icon: Brain,
    color: '#a78bfa',
    bg: 'rgba(167,139,250,0.12)',
    border: 'rgba(167,139,250,0.4)',
    description: 'ML recommendations model',
    category: 'Security & Ops',
  },

  // --- EXTERNAL CLOUD SERVICES ---
  {
    type: 'cloud',
    label: 'Cloud Service',
    icon: Cloud,
    color: '#0ea5e9',
    bg: 'rgba(14,165,233,0.12)',
    border: 'rgba(14,165,233,0.4)',
    description: 'External API (Stripe/SendGrid)',
    category: 'External',
  },
];

export const getComponentConfig = (type) =>
  COMPONENT_TYPES.find((c) => c.type === type) || COMPONENT_TYPES[0];

export const CATEGORIES = [...new Set(COMPONENT_TYPES.map((c) => c.category))];
